// Structure catalog. Placement is drafted, one per day — each entry must be
// a legible decision, not filler.

export const STRUCTURES = {
  farm: {
    id: 'farm',
    name: 'Farm',
    cost: 10,
    hp: 1,
    glowPerSecond: 0.6,
    weight: 3,
    defensive: false,
    description: 'Steady Glow while the sun holds.',
  },
  well: {
    id: 'well',
    name: 'Well',
    cost: 8,
    hp: 1,
    glowPerSecond: 0.2,
    adjacencyBonus: { farm: 0.4 },
    weight: 2,
    defensive: false,
    description: 'A little Glow, and +0.4/s to each neighboring Farm.',
  },
  lantern: {
    id: 'lantern',
    name: 'Lantern',
    cost: 12,
    hp: 1,
    slowsAdjacent: 1.6,
    weight: 2,
    defensive: true,
    description: 'Never targeted \u2014 shades don\u2019t eat light. Lit neighbors: slower attackers, faster banishes, +1 bolt for towers.',
  },
  watchtower: {
    id: 'watchtower',
    name: 'Watchtower',
    cost: 16,
    hp: 1,
    nightCharges: 2,
    weight: 2,
    defensive: true,
    description: 'Two bolts each night burn shades reaching its neighbors. Cannot save itself.',
  },
  palisade: {
    id: 'palisade',
    name: 'Palisade',
    cost: 6,
    hp: 3,
    tauntWeight: 3,
    weight: 2,
    defensive: true,
    description: 'Shields its neighbors: shades strike it instead. Takes three nights of teeth.',
  },
  granary: {
    id: 'granary',
    name: 'Granary',
    cost: 12,
    hp: 1,
    dawnGlow: 6,
    weight: 2,
    defensive: false,
    description: '+6 Glow at every dawn it survives.',
  },
  belltower: {
    id: 'belltower',
    name: 'Bell Tower',
    cost: 12,
    hp: 1,
    nightDelay: 2,
    weight: 1,
    defensive: true,
    description: 'Its toll delays every shade 2s and hastens the Warden\u2019s step.',
  },
  emberKiln: {
    id: 'emberKiln',
    name: 'Ember Kiln',
    cost: 10,
    hp: 1,
    weight: 1,
    defensive: false,
    description: 'At the fall: +1 Ember per 20 Glow held, up to 3.',
  },
  shrine: {
    id: 'shrine',
    name: 'Shrine',
    cost: 12,
    hp: 1,
    weight: 1,
    defensive: false,
    description: 'At the fall: +1 Ember, +1 more per neighbor still standing.',
  },
};

export const STRUCTURE_IDS = Object.keys(STRUCTURES);
